checks:
    php:
        code_rating: true
        remove_extra_empty_lines: true
        remove_php_closing_tag: true
        remove_trailing_whitespace: true
tools:
    external_code_coverage:
        timeout: 1800
        runs: 1
    php_code_coverage: false
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, config, docs]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, config, docs]