language: php
 
php:
  - 5.3
  - 5.4

env:
  - CAKE_VERSION=master
  - CAKE_VERSION=2.1
  - CAKE_VERSION=2.2
  - CAKE_VERSION=2.3
  - CAKE_VERSION=2.5

before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - git clone git://github.com/burzum/Imagine ../plugins/Image
  - cp -R ../FileStorage plugins/FileStorage
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - chmod -R 777 ../cakephp/app/tmp
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php
 
script:
  - ./lib/Cake/Console/cake test FileStorage AllFileStorage --stderr
 
notifications:
  email: false